### ISSUE TITLE
 Color recognition - improve training

### ISSUE THREAD

**Issue by Dayannelopesvieira** [ahmetozlu/color_recognition#1]
Hey, I'm working with something  similar and I wanted to use knn to recognize the colors in "real time". I saw your training data and I would like to know how did you label? (139, 0, 0, red for example)

I'm used to use Image Label to label objects, but with color I got confuse.
Can you help me saying how did you extract these information?

And btw great job.

Thank you

**Comment by ahmetozlu** [comment]
[training_dataset](https://github.com/ahmetozlu/color_recognition/tree/master/src/training_dataset) which contains the training data images. 8 different colors exists in [training_dataset](https://github.com/ahmetozlu/color_recognition/tree/master/src/training_dataset):

- black
- blue
- green
- orange
- red
- violet
- white
- yellow

You can add new images in the appropriate folders to enlarge [training_dataset](https://github.com/ahmetozlu/color_recognition/tree/master/src/training_dataset). For example, in folder red which contains red color training images, you will see 10 different images that are named as red1.jpg, red2.jpg, ... , red10.jpg and the image file names (**_red_**.jpg) are the label for those images.

Let me assume that you want to add new training color which is brown so you should create a new folder which name is brown under [training_dataset](https://github.com/ahmetozlu/color_recognition/tree/master/src/training_dataset) folder. And then you should add brown image files under this path as brown1.jpg, brown2.jpg, ... , brown10.jpg so you added new training images with the labels (labes are the image file name, i.e. **_brown1_**.jpg that are parsed by program as label).

[color_histogram_of_training_image](https://github.com/ahmetozlu/color_recognition/blob/master/src/color_recognition_api/color_histogram_feature_extraction.py#L44) is for feature extraction which extracts the color histogram features using color image files. And you should add new _elif_ statement to add your new training color which is brown, like this:

    def color_histogram_of_training_image(img_name):
	
	    # detect image color by using image file name to label training data
	    if "red" in img_name:
		    data_source = "red"
	    elif "yellow" in img_name:
		    data_source = "yellow"
	    elif "green" in img_name:
		    data_source = "green"
	    elif "orange" in img_name:
		    data_source = "orange"
	    elif "white" in img_name:
		    data_source = "white"
	    elif "black" in img_name:
		    data_source = "black"
	    elif "blue" in img_name:
		    data_source = "blue"
	    elif "violet" in img_name:
		    data_source = "violet"
        elif "brown" in img_name: # you should add it
                data_source = "brown" # you should add it

so you added new color which is brown in your [training_dataset  ](https://github.com/ahmetozlu/color_recognition/tree/master/src/training_dataset) and you are able to extract brown color image features.

The feature and its label was created by the program (via [color_histogram_of_training_image ](https://github.com/ahmetozlu/color_recognition/blob/master/src/color_recognition_api/color_histogram_feature_extraction.py) method).

[This](https://github.com/ahmetozlu/color_recognition/blob/master/src/training.data#L1) is created by program and it means that one of the red images has 139, 0, 0 (R, G, B) features and:

- 139: means the average value of Red pixel color histogram bin
- 0: means the average value of Green pixel color histogram bin
- 0: means the average value of Blue pixel color histogram bin

So you should add training images under appropriate folder and with appropriate file name and then program performs feature extraction and add the labels to create [training.data](https://github.com/ahmetozlu/color_recognition/blob/master/src/training.data) which is created by the program not by you. 

As a summary, you just need to collect training images and locate it under [training_dataset](https://github.com/ahmetozlu/color_recognition/tree/master/src/training_dataset) and modify the [color_histogram_of_training_image](https://github.com/ahmetozlu/color_recognition/blob/master/src/color_recognition_api/color_histogram_feature_extraction.py#L44) method.

**Comment by Dayannelopesvieira** [comment]
Perfect! Thank you very much, you helped me a lot. I will try right now.
