### ISSUE TITLE
error in your code

### ISSUE THREAD

**Issue by fawazsammani** [ahmetozlu/color_recognition#2]
Hi. 
I just realized an error in your code:
You are calculating the Euclidean distance according to length = 2 (meaning only b and g) , you are ignoring the R. What your doing is sqrt[(x2-x1)^2 + (y2-y1)^2] rather than 
sqrt[(x2-x1)^2 + (y2-y1)^2 + (z2-z1)^2]
When you are doing length = len(testInstance) - 1, then since your testInstance length =3, that means you are considering a length of 2 --> so it will be : for I in range (2), and you'll ignore the r channel in that case. Are you intending to do that? As what I know, you should also consider the r channel. 
Thanks

**Comment by ahmetozlu** [comment]
Fixed, thanks a lot! :)
